request:
  host: "![kABnbbpBGoEN9d8oU448teNpPYLx+AtrCdKzn+nTuaDG3cHr0H1tMAdh4n988wg/]"
  port: "![YPjXg756yNU=]"
  client_id: "![RU8UKwa4hrmFRIxHzHpOUVQLrDUzP5lJdmZeWlpt6Fho4+4/c1ycmA==]"
  client_secret: "![8tk0LbpR5166uEy2sfM/ZgK1Pn1U7osnZE8k0xUJ5m9ccT5glO2hJA==]"